### PR TITLE
add sri hash to manifest

### PR DESCRIPTION
**Pull request by josephaxisa**
Generate and add SRI hash to manifest. This is a requirement for extension that is tied to Looker 21.8 or greater. For posterity it can be generated with the following command:
```
openssl dgst -sha384 -binary bundle.js | openssl base64 -A
``` 
It's also a good automation candidate that would be part of the apix deploy script.

### CODE REVIEW

**Review by jkaster — APPROVED** [review]

**Review by bryans99 — CHANGES_REQUESTED** [review]
sir hash is good but manifest is out of date. Should be

```
project_name: "api-explorer"

application: api-explorer {
  label: "API Explorer"
  file: "bundle.js"

  entitlements: {
    local_storage: yes
    navigation: no
    new_window: yes
    new_window_external_urls: ["https://looker.com/*"]
    raw_api_request: yes
    use_form_submit: yes
    use_embeds: yes
    core_api_methods: ["versions", "api_spec"]
    external_api_urls: ["https://raw.githubusercontent.com","http://localhost:30000"]
    oauth2_urls: []
  }
}

constant: CONNECTION_NAME {
  value: ""
  export: override_optional
}

```

**Comment by josephaxisa** [comment]
I can't see what's wrong with the manifest file. It looks like the one above.

**Review by jkaster — APPROVED** [review]
LGTM

**Comment by bryans99** [comment]
Closed in favor of this commit which went straight to master.

https://github.com/looker-open-source/extension-api-explorer/commit/3d0f15dec18014090ff029869bdf2f98fca54287

We need to come up with a process for this

**Pull request closed without merging**
